theme: jekyll-theme-slate
title: Spring Data JPA + Neo4j with Spring Boot und Redis Http Session
description: Demo web project for Spring Boot using Spring Data Neo4j working together with Spring Data JPA in a Web App


